### ISSUE TITLE
Add Pricing Section to README 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/recipe-parser#2]
AppVeyor's pricing: http://www.appveyor.com/pricing $59/month
is **_way better**_ than Travis-CI: https://travis-ci.com/plans $129/month
we need to understand _why_...

**Comment by sofer** [comment]
Possibly Microsoft sees this as a tactically important service and is giving them Azure hosting for free (and other benefits, such as promoting the service heavily through MSDN) to allow them to offer market-clearing pricing.

**Comment by nelsonic** [comment]
Very probable... 
Microsoft are _desperate_ to not miss the Node.js bandwagon: https://msopentech.com/blog/2015/02/10/microsoft-joins-industry-in-move-to-create-node-js-foundation/ 

Still, if AppVeyor can afford to offer such low pricing, might be worth considering.

_However_, **_Codeship**_'s $49/month _unlimited_ builds, _unlimited_ private projects and _unlimited_ team members is pretty compelling... https://codeship.com/pricing

**Comment by nelsonic** [comment]
Closing as we are using `GitHub Actions` to run our CI. ✅
